$schema: "1.0"
name: install-msi
command: './main.ps1 -FilePath {{filePath}}'
parameters:
  filePath:
    default: ''
    type: 'string'
    required: true
    description: | 
      MSI file path absolute path
documentation:
  notes: This task is used to msi packages
  examples:
    - name: msi
      parameters:
        filePath: 'C:\Temp\Everything-1.4.1.1024.x64.msi'